# Generated by Django 3.2.16 on 2023-01-26 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Address3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Address4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Educational_BG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_school_name', models.CharField(max_length=100)),
                ('e_earned', models.CharField(max_length=100)),
                ('e_graduation_date', models.DateTimeField()),
                ('e_honors', models.CharField(max_length=50)),
                ('h_school_name', models.CharField(max_length=100)),
                ('h_earned', models.CharField(max_length=100)),
                ('h_graduation_date', models.DateTimeField()),
                ('h_honors', models.CharField(max_length=50)),
                ('c_school_name', models.CharField(max_length=100)),
                ('c_course', models.CharField(max_length=50)),
                ('c_start_year', models.IntegerField()),
                ('c_end_year', models.IntegerField()),
                ('c_earned', models.CharField(max_length=100)),
                ('c_graduation_date', models.DateTimeField()),
                ('c_honors', models.CharField(max_length=50)),
                ('m_school_name', models.CharField(max_length=100)),
                ('m_course', models.CharField(max_length=50)),
                ('m_start_year', models.IntegerField()),
                ('m_end_year', models.IntegerField()),
                ('m_earned', models.CharField(max_length=100)),
                ('m_graduation_date', models.DateTimeField()),
                ('m_honors', models.CharField(max_length=50)),
                ('d_school_name', models.CharField(max_length=100)),
                ('d_course', models.CharField(max_length=50)),
                ('d_start_year', models.IntegerField()),
                ('d_end_year', models.IntegerField()),
                ('d_earned', models.CharField(max_length=100)),
                ('d_graduation_date', models.DateTimeField()),
                ('d_honors', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ebg_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employment_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_status', models.CharField(max_length=50)),
                ('gsis', models.CharField(max_length=50)),
                ('pagibig', models.CharField(max_length=50)),
                ('philhealth', models.CharField(max_length=50)),
                ('sss', models.CharField(max_length=50)),
                ('tin', models.CharField(max_length=50)),
                ('agency_emp_no', models.CharField(max_length=50)),
                ('date_hired', models.DateTimeField()),
                ('present_designation', models.CharField(max_length=50)),
                ('salary_grade', models.IntegerField()),
                ('skills', models.CharField(max_length=200)),
                ('non_acad_distinction', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='e_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_last_name', models.CharField(max_length=50)),
                ('c_first_name', models.CharField(max_length=50)),
                ('c_middle_name', models.CharField(max_length=50)),
                ('c_birthdate', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='f_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('exam_date', models.DateTimeField()),
                ('exam_place', models.CharField(max_length=100)),
                ('license_no', models.CharField(max_length=50)),
                ('validity_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='l_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.BooleanField(default=False)),
                ('q1_details', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='q_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=50)),
                ('extension_name', models.CharField(max_length=10)),
                ('birthdate', models.DateTimeField()),
                ('birthplace', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('civil_status', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('blood_type', models.CharField(max_length=5)),
                ('citizenship', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField()),
                ('provincial_address', models.CharField(max_length=200)),
                ('if_province', models.BooleanField(default=False)),
                ('telephone_no', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=20)),
                ('s_last_name', models.CharField(max_length=50)),
                ('s_first_name', models.CharField(max_length=50)),
                ('s_middle_name', models.CharField(max_length=50)),
                ('s_extension_name', models.CharField(max_length=10)),
                ('s_occupation', models.CharField(max_length=50)),
                ('s_employer', models.CharField(max_length=50)),
                ('s_business_address', models.CharField(max_length=100)),
                ('s_mobile_no', models.CharField(max_length=20)),
                ('f_last_name', models.CharField(max_length=50)),
                ('f_first_name', models.CharField(max_length=50)),
                ('f_middle_name', models.CharField(max_length=50)),
                ('f_extension_name', models.CharField(max_length=10)),
                ('m_last_name', models.CharField(max_length=50)),
                ('m_first_name', models.CharField(max_length=50)),
                ('m_middle_name', models.CharField(max_length=50)),
                ('address1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='address1', to='records.address1')),
                ('address2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='address2', to='records.address2')),
                ('address3', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='address3', to='records.address3')),
                ('address4', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='address4', to='records.address4')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='education', to='records.educational_bg')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employment', to='records.employment_info')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='family', to='records.family')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='license', to='records.license')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question', to='records.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='address3',
            name='address4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='records.address4'),
        ),
        migrations.AddField(
            model_name='address2',
            name='address3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='records.address3'),
        ),
    ]
