# Generated by Django 3.2.16 on 2023-01-31 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20230130_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='c_birthdate',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='c_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='c_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='c_middle_name',
            new_name='middle_name',
        ),
        migrations.AddField(
            model_name='family',
            name='relation',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
