# Generated by Django 3.2.16 on 2023-01-31 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20230131_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='user',
        ),
    ]
