# Generated by Django 3.2.16 on 2023-01-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_remove_family_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
