# Generated by Django 3.2.16 on 2023-02-20 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20230220_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_info',
            name='education',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='employment',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='question',
        ),
        migrations.AddField(
            model_name='educational_bg',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ebg_account', to='records.personal_info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employment_info',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='e_account', to='records.personal_info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='q_account', to='records.personal_info'),
            preserve_default=False,
        ),
    ]
