# Generated by Django 3.2.16 on 2023-02-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_auto_20230220_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
